/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/walkie_talkie__3d_communication_device.glb -o temp_walkie.jsx 
Author: Gamico (https://sketchfab.com/gamico)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/walkie-talkie-3d-communication-device-d60f0fac1b0d4092aea4aab8eea2587b
Title: Walkie Talkie – 3D Communication Device
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/walkie_talkie__3d_communication_device.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Walkie_Talkie_02__10___Default_0.geometry} material={materials['10___Default']} />
        <mesh geometry={nodes.Walkie_Talkie_02_Walkie_Talkie_02_0.geometry} material={materials.Walkie_Talkie_02} />
      </group>
    </group>
  )
}

useGLTF.preload('/walkie_talkie__3d_communication_device.glb')
